package main

import (
	"context"
	"deplagene/avito-tech-internship/api"
	"deplagene/avito-tech-internship/configs"
	"deplagene/avito-tech-internship/db"
	"deplagene/avito-tech-internship/internal/handler"
	"deplagene/avito-tech-internship/services/pullrequest"
	"deplagene/avito-tech-internship/services/team"
	"deplagene/avito-tech-internship/services/user"
	"deplagene/avito-tech-internship/utils"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
)

func main() {
	// 1. Load Configuration
	cfg := configs.InitConfig()

	// 2. Initialize Logger
	logger := utils.NewLogger(cfg.Env)
	slog.SetDefault(logger) // Set default logger for convenience

	logger.Info("Starting application", "env", cfg.Env, "port", cfg.HTTPPort)

	// 3. Connect to Database
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	pool, err := db.New(ctx, cfg.DatabaseURL)
	if err != nil {
		logger.Error("Failed to connect to database", "error", err)
		os.Exit(1)
	}
	defer pool.Close()
	logger.Info("Connected to database")

	// 4. Initialize Repositories
	teamRepo := team.NewTeamRepository(pool)
	userRepo := user.NewUserRepository(pool)
	prRepo := pullrequest.NewPullRequestRepository(pool)

	// 5. Initialize Services
	teamService := team.NewService(teamRepo, userRepo, pool)
	userService := user.NewService(userRepo, pool)
	prService := pullrequest.NewService(prRepo, userRepo, teamRepo, pool)

	// 6. Create HTTP Handler
	apiHandler := handler.NewHandler(teamService, userService, prService, logger)

	// 7. Setup Chi Router
	router := chi.NewRouter()
	router.Use(middleware.Logger)    // Add Chi's logger middleware
	router.Use(middleware.Recoverer) // Recover from panics

	// Register API routes generated by oapi-codegen
	api.HandlerWithOptions(apiHandler, api.ChiServerOptions{BaseRouter: router})

	// Add health check endpoint
	router.Get("/health", apiHandler.GetHealth)

	// 8. Start HTTP Server
	server := &http.Server{
		Addr:         ":" + cfg.HTTPPort,
		Handler:      router,
		ReadTimeout:  5 * time.Second,
		WriteTimeout: 10 * time.Second,
		IdleTimeout:  120 * time.Second,
	}

	// Graceful shutdown
	go func() {
		sigChan := make(chan os.Signal, 1)
		signal.Notify(sigChan, syscall.SIGINT, syscall.SIGTERM)
		<-sigChan

		logger.Info("Shutting down server...")
		shutdownCtx, shutdownCancel := context.WithTimeout(context.Background(), 30*time.Second)
		defer shutdownCancel()

		if err := server.Shutdown(shutdownCtx); err != nil {
			logger.Error("Server shutdown failed", "error", err)
		}
	}()

	logger.Info("Server listening", "port", cfg.HTTPPort)
	if err := server.ListenAndServe(); err != http.ErrServerClosed {
		logger.Error("Server failed to start", "error", err)
		os.Exit(1)
	}
	logger.Info("Server stopped")
}
